name: CI
on:
- push
- pull_request
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: run pydiatra
      run: |
        python3 -m pip install pydiatra
        python3 -m pydiatra -v .
    - name: run pyflakes
      run: |
        python3 -m pip install pyflakes
        python3 -m pyflakes .
    - name: check README syntax
      run: |
        python3 -m pip install restructuredtext-lint pygments
        rst-lint --level=info --encoding=UTF-8 README
    - name: ensure README is up to date
      run: |
        .private/update-readme
        git diff --exit-code
    - name: download files referenced in README
      run: |
        grep -Po '(?<=<)https:\S+/download/\S+(?=>)' README \
        | wget -O /dev/null -nv -i -
    - name: install archivers
      run: |
        printf 'Apt::Install-Recommends "false";\n' | sudo tee -a /etc/apt/apt.conf
        sudo apt-get update
        sudo apt-get install arc arj cpio lcab libarchive-tools rar zip
        wget http://archive.ubuntu.com/ubuntu/pool/universe/z/zoo/zoo_2.10-28_amd64.deb
        sha256sum -c <<< '953f4f94095ef3813dfd30c8977475c834363aaabce15ab85ac5195e52fd816a  zoo_2.10-28_amd64.deb'
        sudo apt-get install ./zoo_2.10-28_amd64.deb
        rm ./zoo_2.10-28_amd64.deb
    - run: |
        make -C 7zip
    - run: |
        make -C ar
    - run: |
        make -C arc
    - run: |
        make -C arj
    - run: |
        make -C cab
    - run: |
        make -C cpio
    - run: |
        make -C rar
    - run: |
        make -C tar
    - run: |
        make -C zip
    - run: |
        make -C zoo

# vim:ts=2 sts=2 sw=2 et
